-- 코드를 입력하세요
SELECT YEAR(sale.SALES_DATE) AS YEAR, MONTH(sale.SALES_DATE) AS MONTH, user.GENDER, COUNT(DISTINCT user.USER_ID) AS USERS
FROM USER_INFO as user
JOIN ONLINE_SALE as sale ON user.USER_ID = sale.USER_ID
GROUP BY YEAR, MONTH, user.GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR ASC, MONTH ASC, user.GENDER ASC