-- 코드를 입력하세요
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO AS r
JOIN (SELECT r_sub.FOOD_TYPE, MAX(r_sub.FAVORITES) AS f
     FROM REST_INFO AS r_sub
     GROUP BY r_sub.FOOD_TYPE) AS r_join ON r.FAVORITES = r_join.f
GROUP BY r.FOOD_TYPE
ORDER BY r.FOOD_TYPE DESC