-- 코드를 입력하세요

 SELECT DATE_FORMAT(offline.SALES_DATE, '%Y-%m-%d') as SALES_DATE, offline.PRODUCT_ID AS PRODUCT_ID, NULL AS USER_ID, offline.SALES_AMOUNT
 FROM OFFLINE_SALE as offline
 WHERE SALES_DATE LIKE '2022-03%'
UNION ALL
 SELECT DATE_FORMAT(online.SALES_DATE, '%Y-%m-%d') as SALES_DATE ,online.PRODUCT_ID AS PRODUCT_ID ,online.USER_ID AS USER_ID, online.SALES_AMOUNT
 FROM ONLINE_SALE as online
 WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC