-- 코드를 입력하세요
SELECT MONTH(c.START_DATE) AS MONTH, c.CAR_ID, COUNT(c.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS c
JOIN (
    SELECT COUNT(c2.CAR_ID) AS cnt, c2.CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS c2
     WHERE MONTH(c2.START_DATE
                ) >= 8 AND MONTH(c2.START_DATE) <= 10
     GROUP BY c2.CAR_ID
     HAVING cnt >=5
     ) AS c3 ON c.CAR_ID = c3.CAR_ID
WHERE MONTH(c.START_DATE) Between 8 AND 10
GROUP BY c.CAR_ID, MONTH(c.START_DATE)
HAVING RECORDS != 0
ORDER BY MONTH ASC, c.CAR_ID DESC