-- 코드를 입력하세요
SELECT ins.NAME, ins.DATETIME
FROM ANIMAL_INS AS ins
LEFT JOIN ANIMAL_OUTS AS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.ANIMAL_ID is null
GROUP BY ins.NAME, ins.DATETIME
ORDER BY ins.DATETIME ASC
LIMIT 3