-- 코드를 입력하세요
SELECT DISTINCT users.USER_ID, users.NICKNAME, sum(boards.price) as TOTAL_SALES
FROM USED_GOODS_BOARD AS boards
JOIN USED_GOODS_USER AS users ON boards.WRITER_ID = users.USER_ID AND boards.STATUS = 'DONE'
GROUP BY boards.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC