-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS m
JOIN REST_REVIEW AS r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = (SELECT r2.MEMBER_ID
      FROM REST_REVIEW as r2
      GROUP BY r2.MEMBER_ID
      ORDER BY count(r2.MEMBER_ID) DESC
      LIMIT 1)
ORDER BY REVIEW_DATE ASC, r.REVIEW_TEXT ASC