-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r2.REVIEW_TEXT, DATE_FORMAT(r2.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE as m
JOIN (SELECT rank() over (order by COUNT(r.MEMBER_ID) desc) as ranking, r.MEMBER_ID
     FROM REST_REVIEW as r
     GROUP BY r.MEMBER_ID
     ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC) as r1 ON r1.MEMBER_ID = m.MEMBER_ID AND r1.ranking = 1
JOIN REST_REVIEW as r2 ON r1.MEMBER_ID = r2.MEMBER_ID
ORDER BY r2.REVIEW_DATE ASC, r2.REVIEW_TEXT ASC