# -- 코드를 입력하세요
SELECT b.CATEGORY , SUM(sale.SALES) AS TOTAL_SALES
FROM BOOK_SALES as sale
JOIN BOOK as b ON b.BOOK_ID = sale.BOOK_ID
WHERE sale.SALES_DATE LIKE '2022-01-%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC

# SELECT *
# FROM BOOK as b
# # WHERE b.PUBLISHED_DATE LIKE '20%'x