-- 코드를 입력하세요
SELECT author.AUTHOR_ID, author.AUTHOR_NAME, book.CATEGORY, SUM(book.PRICE * sales.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS sales
JOIN BOOK AS book ON book.BOOK_ID = sales.BOOK_ID
JOIN AUTHOR as author ON author.AUTHOR_ID = book.AUTHOR_ID
WHERE sales.SALES_DATE LIKE '2022-01%'
GROUP BY book.CATEGORY, author.AUTHOR_NAME, author.AUTHOR_ID
ORDER BY author.AUTHOR_ID ASC, book.CATEGORY DESC