-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (p.PRICE * SUM(o.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS p
JOIN OFFLINE_SALE AS o ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC