-- 코드를 입력하세요
SELECT p.PRODUCT_ID AS PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * o1.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
JOIN (SELECT o.PRODUCE_DATE, o.PRODUCT_ID, SUM(o.AMOUNT) AS amount
     FROM FOOD_ORDER AS o
     WHERE MONTH(o.PRODUCE_DATE) = 5 AND YEAR(o.PRODUCE_DATE) = 2022
     GROUP BY o.PRODUCT_ID) AS o1 ON p.PRODUCT_ID = o1.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
     