-- 코드를 입력하세요
SELECT product.PRODUCT_ID, product.PRODUCT_NAME, SUM(o.AMOUNT) * product.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS product
JOIN FOOD_ORDER AS o ON o.PRODUCT_ID = product.PRODUCT_ID
WHERE MONTH(o.PRODUCE_DATE) = 5 AND YEAR(o.PRODUCE_DATE) = 2022
GROUP BY product.PRODUCT_ID, product.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, product.PRODUCT_ID ASC